# Generated by Django 3.1.4 on 2021-01-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submit',
            options={'permissions': (('about', 'about'),)},
        ),
    ]
